### ISSUE TITLE
Question about Linear Approximation SARSA

### ISSUE THREAD

**Issue by burmecia** [ceteke/RL#1]
When updating `w` for non-terminal state, why use this:

```python
w += alpha*(reward - discount*q_hat_next)*q_hat_grad
```

rather than using the TD error (from Sutton's book v2 page 244, Episodic Semi-gradient Sarsa) like below?

```python
w += alpha*(reward + discount*q_hat_next - q_hat)*q_hat_grad
```

**Comment by ceteke** [comment]
You are right, thank you for pointing that out.
